/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mthqvmpvogzcsnzvikko"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10aHF2bXB2b2d6Y3NuenZpa2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMTY3NTMsImV4cCI6MjA4NTY5Mjc1M30.jNct-c3D-HRYlhbsbuItxnw76PBWh9ntuYB8854yvh0"